### ISSUE TITLE
Feature: Allow logs to be made private

### ISSUE THREAD

**Issue by kry0sc0pic** [memory-stack/Memory-Stack#27]
I was scrolling through the reddit comments on the post for memory stack and a lot of people wanted to be able to keep their logs private so I wanted to suggest it.

command to set profile private could something be like `mstak public false`

**Comment by void-memories** [comment]
> I was scrolling through the reddit comments on the post for memory stack and a lot of people wanted to be able to keep their logs private so I wanted to suggest it.
> 
> command to set profile private could something be like `mstak public false`

It can be handled in one of two ways.
1. logs of private accounts don't show up on the homepage, hence no one will discover that user. Kind of pseudo-private.
2. add a login system on the website such that only the user with the proper credentials would be able to see their logs. 

What would you prefer?

**Comment by kry0sc0pic** [comment]
Since the website provides the only way to view personal logs of the past, I would prefer the second one.
